RSRESET
PLAYER_POSX        RW 1
PLAYER_SPEEDX      RW 1
PLAYER_POSY        RW 1
PLAYER_SPEEDY      RW 1
PLAYER_STATE       RB 1
PLAYER_ANIM        RB 1
PLAYER_ANIM_CTR    RB 1
PLAYER_MAP_PTR     RW 1
PLAYER_STRUCT_SIZE RB 1